### PR TITLE
fictive changes. going to test pipeline

### PR DESCRIPTION
**Pull request by vmeshche**
fictive changes. going to test pipeline

### CODE REVIEW

**Comment by napetrov** [comment]
Mac build failing - interesting.  I don't think this happened due to your change. might be something with Mac env in AWS

**Comment by vmeshche** [comment]
yes. looks like env problems. 
this is strange. we need the ability to restart it.

**Comment by napetrov** [comment]
> 
> 
> yes. looks like env problems.
> this is strange. we need the ability to restart it.

you can go to the details of failed check and rerun it

**Comment by napetrov** [comment]
please test me

**Pull request closed without merging**
